name: trans
channels:
  - conda-forge
  - pytorch
  - defaults
dependencies:
  - python>=3.11
  - pip
  - pytorch>=2.1.0
  - torchvision
  - numpy>=1.24.3
  - pillow>=10.0.0
  - pip:
    - easyocr>=1.7.1
    - langchain>=0.0.352
    - openai>=1.3.7
    - PyPDF2>=3.0.1
    - streamlit>=1.29.0
    - streamlit-pdf-viewer>=0.0.3
    - python-dotenv>=1.0.0
    - requests>=2.31.0
    - pyyaml>=6.0.1
    - transformers>=4.36.0
    - python-docx>=1.0.1
